# Generated by Django 5.0.6 on 2024-06-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewschedule',
            name='access_code',
        ),
        migrations.RemoveField(
            model_name='interviewschedule',
            name='conference_id',
        ),
        migrations.AlterField(
            model_name='speciality',
            name='school',
            field=models.CharField(choices=[('School of Management', 'Школа Менеджмента'), ('School of Economics and Finance', 'Школа Экономики и Финансов'), ('School of Politics and Law', 'Школа Политики и Права'), ('Urbanism Center', 'Центр Урбанистики'), ('School of Hospitality and Tourism', 'Школа Гостеприимства и Туризма'), ('School of Digital Technologies', 'Школа Цифровых Технологий'), ('School of Entrepreneurship and Innovation', 'Школа Предпринимательства и Инноваций'), ('School of Media and Cinema', 'Школа Медиа и Кино'), ('Sharmanov School of Health Sciences', 'Sharmanov School of Health Sciences'), ('Sports Management Center', 'Центр Спортивного Менеджмента')], max_length=255),
        ),
    ]
