# Generated by Django 5.0.6 on 2024-06-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_application_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
